<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251204114818 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tags (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tour (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, startdate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, enddate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, travel_companion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6AD1F969FF3FFE7A ON tour (travel_companion_id)');
        $this->addSql('CREATE TABLE tour_tags (tour_id INT NOT NULL, tags_id INT NOT NULL, PRIMARY KEY (tour_id, tags_id))');
        $this->addSql('CREATE INDEX IDX_4E8C740615ED8D43 ON tour_tags (tour_id)');
        $this->addSql('CREATE INDEX IDX_4E8C74068D7B4FB4 ON tour_tags (tags_id)');
        $this->addSql('CREATE TABLE travel_companion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, birthday DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE tour ADD CONSTRAINT FK_6AD1F969FF3FFE7A FOREIGN KEY (travel_companion_id) REFERENCES travel_companion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tour_tags ADD CONSTRAINT FK_4E8C740615ED8D43 FOREIGN KEY (tour_id) REFERENCES tour (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tour_tags ADD CONSTRAINT FK_4E8C74068D7B4FB4 FOREIGN KEY (tags_id) REFERENCES tags (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tour DROP CONSTRAINT FK_6AD1F969FF3FFE7A');
        $this->addSql('ALTER TABLE tour_tags DROP CONSTRAINT FK_4E8C740615ED8D43');
        $this->addSql('ALTER TABLE tour_tags DROP CONSTRAINT FK_4E8C74068D7B4FB4');
        $this->addSql('DROP TABLE tags');
        $this->addSql('DROP TABLE tour');
        $this->addSql('DROP TABLE tour_tags');
        $this->addSql('DROP TABLE travel_companion');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
